sudo: false
git:
  depth: 3
branches:
  only:
  - gh-pages
  - /.*/
language: node_js
node_js:
- node
cache:
  directories:
  - "$HOME/.npm"
  - node_modules
install:
- npm install
before_script:
- npm install -g gulp-cli
script: gulp
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    local_dir: app
    on:
      branch: master
  - provider: npm
    email: ingo.reinhart@chefkoch.de
    api_key: "$NPMJS_TOKEN"
    skip_cleanup: true
    on:
      tags: true
      repo: chefkoch-dev/design-system
